In [20]:
import numpy as np


In [2]:
x = np.empty((2,2))
x

array([[4.80999553e-310, 0.00000000e+000],
       [2.90435030e-144, 6.95045478e-310]])

In [3]:
x = np.ones((4,2))
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
x=np.full((4,3),3)

In [5]:
p=np.arange(6).reshape(2,3)
a=np.zeros_like(p)
a

array([[0, 0, 0],
       [0, 0, 0]])

In [6]:
p=np.arange(8).reshape(2,4)
x=np.ones_like(p)
x

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [8]:
new_list=[1,2,3,4]
K=np.array(new_list)
K

array([1, 2, 3, 4])

In [9]:
b=np.arange(10,50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
b=np.arange(0,9).reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
b=np.eye(3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
x = np.random.random(30)
mean = x.mean()

print("array given: ", x)
print("Mean  : ", mean)

array given:  [0.12262054 0.0210297  0.46282705 0.70633054 0.78558176 0.30177117
 0.37554117 0.95832471 0.82311485 0.32177844 0.16866981 0.93444289
 0.85794062 0.59899547 0.07649762 0.93910481 0.78400786 0.309088
 0.62120494 0.29930206 0.87224955 0.70338835 0.44650292 0.67679526
 0.64545454 0.30878872 0.60299671 0.40633694 0.58735154 0.85670702]
Mean  :  0.5524915190603378


In [22]:
b=np.random.random((10,10))
min=b.min()
max=b.max()
print("Array: ", b)
print("Min:", min)
print("Max:", max)

Array:  [[0.68375613 0.35290788 0.47697783 0.89361447 0.67720571 0.90057415
  0.82930335 0.41088837 0.5521172  0.02960759]
 [0.51449906 0.12130846 0.09684859 0.02410436 0.33130057 0.89026558
  0.98087229 0.99211026 0.88803923 0.92786551]
 [0.91637441 0.26063056 0.14160473 0.02235332 0.71207738 0.01279746
  0.62835815 0.012999   0.21151006 0.31045696]
 [0.86582549 0.1217277  0.34296526 0.68553286 0.42841714 0.53990729
  0.26682739 0.16145212 0.89343123 0.21599632]
 [0.08725661 0.59331384 0.12505718 0.30494413 0.60400406 0.47120886
  0.47800706 0.57427743 0.26395225 0.54748672]
 [0.32058125 0.97062743 0.69943196 0.10894211 0.58928846 0.3445818
  0.18723843 0.79218639 0.72207638 0.43187937]
 [0.65938805 0.37003617 0.06346748 0.58059743 0.01976501 0.69078399
  0.90875664 0.77374664 0.71104977 0.8061166 ]
 [0.99370185 0.36078381 0.17755809 0.79925541 0.52694069 0.89053485
  0.21008486 0.73328116 0.99855619 0.52501246]
 [0.3159216  0.06515351 0.18626863 0.22710065 0.47644146 0.61584379
  0.2

In [23]:
b=np.zeros(10)
b[4]=1
print("Updated :", b)

Updated : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [24]:
b=np.array([1,2,0,0,4,0])
rev=b[::-1]
print("Original: ", b)
print("reversed: ", rev)

Original:  [1 2 0 0 4 0]
reversed:  [0 4 0 0 2 1]


In [25]:
b=np.zeros((5,5),dtype=int)
b[0,:]=1 #top
b[-1,:]=1 #bottom
b[:,0]=1 #left
b[:,-1]=1 #right
print("1 on border and 0 inside : ",b)


1 on border and 0 inside :  [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [26]:
b=np.zeros((8,8))
b[1::2,::2]=1
b[::2,1::2]=1
b

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [28]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
x3 = np.array([9,10])
y3 = np.array([11,12])
print("x: \n",x)
print("y: \n",y)
add=x+y
add3=x3+y3
print("Adding x+y: \n",add)
print("x3: \n",x3)
print("y3: \n",y3)
print("adding x3+y3: ",add3)

x: 
 [[1 2]
 [3 5]]
y: 
 [[5 6]
 [7 8]]
Adding x+y: 
 [[ 6  8]
 [10 13]]
x3: 
 [ 9 10]
y3: 
 [11 12]
adding x3+y3:  [20 22]


In [29]:
sub=x-y
sub3=x3-y3
print("subtracting y from x: ",sub)
print("subtracting y3 from x3: ",sub3)

subtracting y from x:  [[-4 -4]
 [-4 -3]]
subtracting y3 from x3:  [-2 -2]


In [30]:
mul_x=x*2
mul_x
mul_y=y*2
mul_y
mul_x3=x3*2
mul_x3
mul_y3=y3*2
mul_y3

array([22, 24])

In [31]:
sq_x=np.square(x)
print("squaring x: \n",sq_x )
sq_y=np.square(y)
print("squaring y: \n",sq_y )
sq_x3=np.square(x3)
print("squaring x3: \n",sq_x3 )
sq_y3=np.square(y3)
print("squaring y3: \n",sq_y3 )

squaring x: 
 [[ 1  4]
 [ 9 25]]
squaring y: 
 [[25 36]
 [49 64]]
squaring x3: 
 [ 81 100]
squaring y3: 
 [121 144]


In [32]:
result = np.dot(x3, y3)
result
result_1 = np.dot(x, x3)
result_1
result_2 = np.dot(x, y)
result_2


array([[19, 22],
       [50, 58]])

In [33]:
a=np.concatenate((x,y),axis=1)
print(a)
a=np.vstack((x3,y3))
print(a)

[[1 2 5 6]
 [3 5 7 8]]
[[ 9 10]
 [11 12]]


In [35]:
result = np.concatenate((x, x3))
print("Concatenation result:\n", result)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

x and x3 have different dimension


In [38]:

A1=np.array([[3,4],[7,8]])
B1=np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A1)
result=np.dot(A1,A_inverse)
identity_matrix=np.eye(2)
print("Matrix A1:\n", A1)
print("Inverse of A1 (A^-1):\n", A_inverse)
print("Product of A1 and A^-1 (A.A^-1):\n", result)
print("Identity Matrix:\n", identity_matrix)
y=np.allclose(result,identity_matrix)
print("Is A.A^-1 equal to identity matrix?->",y)


Matrix A1:
 [[3 4]
 [7 8]]
Inverse of A1 (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product of A1 and A^-1 (A.A^-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A.A^-1 equal to identity matrix?-> True


In [39]:
A1B1 = np.dot(A1, B1)
B1A1 = np.dot(B1, A1)
print("A1B1 (A1 * B1):\n", A1B1)
print("B1A1 (B1 * A1):\n", B1A1)
are_equal=np.array_equal(A1B1,B1A1)
print(" Is A1B1 = B1A1? ",are_equal)

A1B1 (A1 * B1):
 [[23 13]
 [51 29]]
B1A1 (B1 * A1):
 [[36 44]
 [13 16]]
 Is A1B1 = B1A1?  False


In [40]:
A1 = np.array([[1, 2], [3, 4]])
B1 = np.array([[5, 6], [7, 8]])
AB=np.dot(A1,B1)
AB_T=AB.T
B_T=B1.T
A_T=A1.T
BT_AT=np.dot(B_T,A_T)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T * A^T:\n", BT_AT)
is_equal=np.array_equal(AB_T,BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", is_equal)

AB:
 [[19 22]
 [43 50]]
(AB)^T:
 [[19 43]
 [22 50]]
B^T:
 [[5 7]
 [6 8]]
A^T:
 [[1 3]
 [2 4]]
B^T * A^T:
 [[19 43]
 [22 50]]
Is (AB)^T equal to B^T * A^T?  True


In [41]:

A1=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B1=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A1)
x=np.dot(A_inverse,B1)
print( A1)
print( B1)
print( A_inverse)
print( x)

[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
[-1 -3  9]
[[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
[ 2.  1. -2.]


In [43]:

import time
l3=list(range(1,1000001))
l4=list(range(1,1000001))
start_time= time.time()
result_list=[a+b for a, b in zip(l3,l4)]
python_time=time.time()-start_time
print(" Python lists time:", python_time, "seconds")
#numpy arrays:
a3=np.arange(1,1000001)
a4=np.arange(1,1000001)

start_time=time.time()
result_array=a3+a4
numpy_time=time.time()-start_time
print(" NumPy arrays time:", numpy_time, "seconds")



 Python lists time: 0.09642195701599121 seconds
 NumPy arrays time: 0.006551980972290039 seconds


In [44]:

start_time=time.time()
result_list=[a*b for a,b in zip(l3,l4)]
python_time=time.time()-start_time
print("multiplication using Python lists time:", python_time, "seconds")

start_time = time.time()
result_array = a3 * a4
numpy_time = time.time() - start_time
print(" multiplication using NumPy arrays:", numpy_time, "seconds")


multiplication using Python lists time: 0.23655915260314941 seconds
 multiplication using NumPy arrays: 0.006798744201660156 seconds


In [48]:



start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(l3, l4))
python_time = time.time() - start_time
print( python_time, "seconds")



start_time = time.time()
dot_product_numpy = np.dot(a3, a4)
numpy_time = time.time() - start_time
print( numpy_time, "seconds")

0.11213231086730957 seconds
0.002195596694946289 seconds


In [49]:
import time
import numpy as np

# Python lists
m3 = [[i for i in range(100)] for j in range(100)]
m4 = [[i for i in range(100)] for j in range(100)]

start_time = time.time()
result_matrix = [[sum(m3[i][k] * m4[k][j] for k in range(100)) for j in range(100)] for i in range(100)]
python_time = time.time() - start_time
print(" Python lists time:", python_time, "seconds")

# Matrix multiplication using NumPy
m3_np = np.random.rand(100, 100)
m4_np = np.random.rand(100, 100)

start_time = time.time()
result_matrix_np = np.dot(m3_np, m4_np)
numpy_time = time.time() - start_time
print("MNumPy arrays time:", numpy_time, "seconds")


Matrix multiplication using Python lists time: 0.40896129608154297 seconds
Matrix multiplication using NumPy arrays time: 0.0063970088958740234 seconds
